### ISSUE TITLE
Number.isNaN is not supported on all browsers

### ISSUE THREAD

**Issue by gkontokotsios** [jdpedrie/angularjs-ordinal-filter#10]
Number.NaN on Safari and IE doesn't work and causes exceptions.
Code to review is: ordinal-browser.js:30
```
function numeric(n) {
  return 'number' === typeof +n && !Number.isNaN(+n);
}
```
The above can simply be changed to:
```
function numeric(n) {
  return 'number' === typeof +n && !isNaN(+n);
}
```
The above issue affects version 2.1

**Comment by jdpedrie** [comment]
Thanks for the heads up. I'll publish this as 2.2 shortly.
