### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by bcherny** [jdpedrie/angularjs-ordinal-filter#5]

**Comment by bcherny** [comment]
@jdpedrie those tests don't guarantee much. you need to test a wider range of inputs and domain of outputs. here's an example - https://github.com/npm/node-semver/blob/master/test/index.js#L78

**Comment by jdpedrie** [comment]
Thanks @bcherny. I added tests for `1` through `30`. I think that should be representative enough?

**Comment by stephenplusplus** [comment]
No need to test more. We're using an ordinal module now, it's not our responsibility to test it.
