### ISSUE TITLE
Does not work at all.

### ISSUE THREAD

**Issue by haffmaestro** [jdpedrie/angularjs-ordinal-filter#7]
Hi, since you updated the bower release this does no longer work, it does not make anything ordinal. I was using it before and it was working so smoothly, I had to fork it and go back to commits, to when your main was ordinal.js in order for it to work again.

Thanks for that code though, it works very nicely.

**Comment by jdpedrie** [comment]
Thanks the the heads up. Check 7b7faa2df907d9df4cd0e626744c97139ebf23c4 and v2.1. Sorry for the inconvenience.
